name: simra

services:
    simra-frontend:
        container_name: simra-frontend
        image: simra/simra-frontend:latest
        build:
            context: .
            dockerfile: Dockerfile
            target: production
            args:
                SIMRA_API_URL: ${SIMRA_API_URL}
        ports:
        - "4200:80"
        env_file:
            -   .env
