name: simra

services:
    simra-frontend:
        container_name: simra-frontend
        image: codinggandalf/simra-frontend:latest
        pull_policy: always
        build:
            context: .
            target: local_production
            dockerfile: Dockerfile
            args:
                SIMRA_API_URL: ${SIMRA_API_URL}
                MAPILLARY_URL: ${MAPILLARY_URL}
                MAPILLARY_ACCESS_TOKEN: ${MAPILLARY_ACCESS_TOKEN}
        ports:
        - "4200:80"
        env_file:
            -   .env
