import { ETrafficTimes } from '@simra/common-models';
import { MapSelectOptions } from '../interfaces/map-select-options.interface';

export const TrafficTimesToLabels: Record<ETrafficTimes, MapSelectOptions & { includesRushHour?: boolean}> = {
	[ETrafficTimes.ALL_DAY]: {
		label: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.LABEL.ALL_DAY',
		tooltip: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.TOOLTIP.ALL_DAY',
	},
	[ETrafficTimes.EARLY_RUSH_HOUR]: {
		label: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.LABEL.EARLY_RUSH_HOUR',
		tooltip: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.TOOLTIP.EARLY_RUSH_HOUR',
		includesRushHour: true,
	},
	[ETrafficTimes.EVENING_NIGHT_MORNING]: {
		label: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.LABEL.EVENING_NIGHT_MORNING',
		tooltip: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.TOOLTIP.EVENING_NIGHT_MORNING',
	},
	[ETrafficTimes.LATE_RUSH_HOUR]: {
		label: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.LABEL.LATE_RUSH_HOUR',
		tooltip: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.TOOLTIP.LATE_RUSH_HOUR',
		includesRushHour: true,
	},
	[ETrafficTimes.MID_DAY]: {
		label: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.LABEL.MID_DAY',
		tooltip: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.TOOLTIP.MID_DAY',
	},
}
