import { ETrafficTimes } from '../enums/traffic-times.enum';
import { MapSelectOptions } from '../interfaces/map-select-options.interface';

export const TrafficTimesToLabels: Record<ETrafficTimes, MapSelectOptions & { includesRushHour?: boolean}> = {
	[ETrafficTimes.ALL_DAY]: {
		label: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.LABEL.ALL_DAY',
		tooltip: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.TOOLTIP.ALL_DAY',
	},
	[ETrafficTimes.EARLY_MORNING]: {
		label: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.LABEL.EARLY_MORNING',
		tooltip: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.TOOLTIP.EARLY_MORNING',
		includesRushHour: true,
	},
	[ETrafficTimes.EARLY_RUSH_HOUR]: {
		label: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.LABEL.EARLY_RUSH_HOUR',
		tooltip: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.TOOLTIP.EARLY_RUSH_HOUR',
		includesRushHour: true,
	},
	[ETrafficTimes.LATE_MORNING]: {
		label: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.LABEL.LATE_MORNING',
		tooltip: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.TOOLTIP.LATE_MORNING',
	},
	[ETrafficTimes.EARLY_AFTERNOON]: {
		label: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.LABEL.EARLY_AFTERNOON',
		tooltip: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.TOOLTIP.EARLY_AFTERNOON',
	},
	[ETrafficTimes.AFTERNOON]: {
		label: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.LABEL.AFTERNOON',
		tooltip: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.TOOLTIP.AFTERNOON',
		includesRushHour: true,
	},
	[ETrafficTimes.LATE_RUSH_HOUR]: {
		label: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.LABEL.LATE_RUSH_HOUR',
		tooltip: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.TOOLTIP.LATE_RUSH_HOUR',
		includesRushHour: true,
	},
	[ETrafficTimes.EVENING]: {
		label: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.LABEL.EVENING',
		tooltip: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.TOOLTIP.EVENING',
		includesRushHour: true,
	},
	[ETrafficTimes.LATE_EVENING]: {
		label: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.LABEL.LATE_EVENING',
		tooltip: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.TOOLTIP.LATE_EVENING',
	},
	[ETrafficTimes.NIGHT]: {
		label: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.LABEL.NIGHT',
		tooltip: 'COMPONENTS.MOLECULES.DANGEROUS_SCORE_BAR.TRAFFIC_TIMES.TOOLTIP.NIGHT',
	},
}
