/**
 * Hints which type of bike was used.
 */
export enum EBikeType {
	NOT_CHOSEN= "NOT_CHOSEN",
	CITY_TREKKING_BIKE = "CITY_TREKKING_BIKE",
	ROAD_RACING_BIKE = "ROAD_RACING_BIKE",
	E_BIKE = "E_BIKE",
	RECUMBENT_BICYCLE = "RECUMBENT_BICYCLE",
	FREIGHT_BICYCLE = "FREIGHT_BICYCLE",
	TANDEM_BICYCLE = "TANDEM_BICYCLE",
	MOUNTAIN_BIKE = "MOUNTAIN_BIKE",
	OTHER = "OTHER"
}
