/**
 * Indicates the type of incident that occurred.
 */
export enum EIncidentType {
	DUMMY_INCIDENT = "DUMMY_INCIDENT",
	NOTHING = "NOTHING",
	CLOSE_PASS = "CLOSE_PASS",
	PULLING_IN_OUT = "PULLING_IN_OUT",
	NEAR_LEFT_RIGHT_HOOK = "NEAR_LEFT_RIGHT_HOOK",
	HEAD_ON_APPROACH = "HEAD_ON_APPROACH",
	TAILGATING = "TAILGATING",
	NEAR_DOORING = "NEAR_DOORING",
	DODGING_OBSTACLE = "DODGING_OBSTACLE",
	OTHER = "OTHER"
}
